---
- name: Include OS-specific variables
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution }}.yml"  # Distribution specific (e.g. Ubuntu.yml)
        - "{{ ansible_os_family }}.yml"     # OS family (e.g. Debian.yml)
        - "default.yml"                     # Default fallback
      paths:
        - "vars"

- name: Include initial setup tasks
  ansible.builtin.include_tasks: setup-0-initial.yml
  tags: [initial]

- name: Set timezone
  timezone:
    name: "{{ timezone }}"
  when: timezone | length > 0

- name: Include sysctl tasks
  ansible.builtin.include_tasks: setup-1-sysctl.yml
  when: emqx_sysctl_enabled | default(true) | bool
  tags: [sysctl]

- name: Configure firewall for EMQX(4370|5730)
  ansible.builtin.include_tasks: setup-2-firewall.yml
  tags: [firewall]

- name: Include chrony tasks
  ansible.builtin.include_tasks: setup-3-chrony.yml
  when: emqx_chrony_enabled | default(true) | bool
  tags: [chrony]

- name: Include OS-specific tasks
  ansible.builtin.include_tasks: "setup-4-{{ ansible_os_family | lower }}.yml"

- name: Include EMQX-Setup tasks
  ansible.builtin.include_tasks: setup-5-emqx.yml
  tags: [emqx]

- name: Include Guard-Pro plugin
  ansible.builtin.include_tasks: setup-6-plugin.yml
  when: emqx_guard_pro_enabled | default(true) | bool
  tags: [plugins]
