---

- name: Set locale
  ansible.builtin.copy:
    content: |
      LANG={{ effective_locale }}
      LANGUAGE={{ emqx_language }}
      LC_ALL={{ effective_locale }}
    dest: "/etc/locale.conf"
    owner: root
    group: root
    mode: '0644'

- name: Setup EMQX package
  ansible.builtin.include_tasks: packages/redhat.yml
