---

- name: Configure EMQX service restart settings
  ansible.builtin.lineinfile:
    path: /lib/systemd/system/emqx.service
    regexp: "^Restart="
    line: "Restart={{ emqx_service_restart }}"
    state: present
  register: restart_config

- name: Configure EMQX service restart delay
  ansible.builtin.lineinfile:
    path: /lib/systemd/system/emqx.service
    regexp: "^RestartSec="
    line: "RestartSec={{ emqx_service_restart_sec }}"
    state: present
  register: restart_delay_config

- name: Reload systemd daemon if service config changed
  ansible.builtin.systemd:
    daemon_reload: true
  when: restart_config.changed or restart_delay_config.changed

- name: Create EMQX configuration
  ansible.builtin.template:
    src: emqx.conf.j2
    dest: /etc/emqx/emqx.conf
    owner: emqx
    group: emqx
    mode: '0644'
  notify: Restart EMQX

- name: Ensure EMQX service's state
  ansible.builtin.service:
    name: emqx
    state: "{{ emqx_service_state }}"
    enabled: "{{ emqx_service_enabled }}"

- name: Wait for EMQX tcp port to be ready
  ansible.builtin.wait_for:
    port: "{{ emqx_tcp_port }}"
    timeout: 3000
  when: emqx_tcp_port != 0

- name: Wait for EMQX dashboard HTTP to be ready
  ansible.builtin.uri:
    url: "http://127.0.0.1:{{ emqx_dashboard_http_port }}/status"
    method: GET
    status_code: 200
  register: dashboard_http_status
  retries: 10
  delay: 5
  until: dashboard_http_status.status == 200
  changed_when: false
  when: emqx_dashboard_http_port is defined and emqx_dashboard_http_port != 0

- name: Wait for EMQX dashboard HTTPS to be ready
  ansible.builtin.uri:
    url: "https://127.0.0.1:{{ emqx_dashboard_https_port }}/status"
    method: GET
    status_code: 200
  register: dashboard_https_status
  retries: 10
  delay: 5
  until: dashboard_https_status.status == 200
  changed_when: false
  when: emqx_dashboard_https_port is defined and emqx_dashboard_https_port != 0

- name: Join EMQX cluster manually when discovery strategy is manual
  ansible.builtin.command: "emqx ctl cluster join emqx@{{ emqx_cluster_initial_hostname }}"
  register: join_result
  when:
    - emqx_cluster_discovery_strategy == "manual"
    - emqx_cluster_initial_hostname is defined
  changed_when: false
  failed_when: >
    join_result.stdout is not search('Ignore') and
    join_result.stdout is not search('successfully') and
    join_result.stdout is not search('already_in_cluster')

- name: Wait for cluster formation
  ansible.builtin.command: emqx ctl cluster status --json
  register: cluster_status
  until: >
    (cluster_status.stdout | from_json).running_nodes | length ==
    (groups['all'] | length)
  retries: 10
  delay: 5
  changed_when: false
  when:
    - emqx_cluster_discovery_strategy == "static" or
      (emqx_cluster_discovery_strategy == "manual" and emqx_cluster_initial_hostname is defined)

- name: Print cluster status on retry failure
  ansible.builtin.debug:
    msg: "Cluster formation failed after retries. Current status: {{ cluster_status.stdout }}"
  when: cluster_status is failed

- name: Display cluster status
  ansible.builtin.debug:
    var: cluster_status.stdout_lines
  when:
    - emqx_cluster_discovery_strategy == "static" or
      (emqx_cluster_discovery_strategy == "manual" and emqx_cluster_initial_hostname is defined)
