---
- name: Configure chrony
  ansible.builtin.template:
    src: chrony.conf.j2
    dest: "{{ chrony_conf_path }}"
    mode: '0644'
  notify: Restart Chronyd

- name: Ensure chronyd service is running
  ansible.builtin.service:
    name: chronyd
    state: started
    enabled: yes
