---

- name: Set locale
  ansible.builtin.copy:
    content: |
      LANG={{ effective_locale }}
      LANGUAGE={{ emqx_language }}
      LC_ALL={{ effective_locale }}
    dest: "/etc/locale.conf"
    owner: root
    group: root
    mode: '0644'

- name: Remove curl-minimal package if present
  ansible.builtin.dnf:
    name: curl-minimal
    state: absent
  when: >
    ansible_distribution_major_version == '9' or
    (ansible_distribution == 'Amazon' and ansible_distribution_version == '2023')

- name: Debug service manager and virtualization type
  ansible.builtin.debug:
    msg: >
      Service Manager: {{ ansible_service_mgr }}
      Virtualization Type: {{ ansible_virtualization_type }}

- name: Set a hostname specifying strategy
  ansible.builtin.hostname:
    name: "{{ emqx_hostname }}"
  become: true
  when: ansible_service_mgr == 'systemd' and ansible_virtualization_type != 'docker'

- name: Setup EMQX package
  ansible.builtin.include_tasks: packages/redhat.yml
