---
# Stop and disable EMQX service
- name: Stop and disable EMQX service
  ansible.builtin.service:
    name: emqx
    state: stopped
    enabled: false
  failed_when: false

- name: Purge EMQX completely including configuration files
  ansible.builtin.apt:
    name: emqx
    state: absent
    purge: yes
    autoremove: yes
  become: true
  when: ansible_os_family == 'Debian'
  failed_when: false

- name: Purge EMQX completely including configuration files
  ansible.builtin.dnf:
    name: emqx
    state: absent
    autoremove: yes
  become: true
  when: ansible_os_family == 'RedHat'

- name: Remove EMQX package
  ansible.builtin.package:
    name: emqx
    state: absent
  vars:
    ansible_pkg_mgr: "{{ 'apt' if ansible_os_family == 'Debian' else 'dnf' }}"

- name: Remove EMQX directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/emqx
    - /var/lib/emqx
    - /var/log/emqx
    - /usr/lib/emqx
    - /tmp/emqx-{{ emqx_version }}

- name: Remove repository configuration
  ansible.builtin.file:
    path: "{{ repo_path }}"
    state: absent
  vars:
    repo_path: >-
      {%- if ansible_os_family == 'Debian' -%}
      /etc/apt/sources.list.d/emqx.list
      {%- else -%}
      /etc/yum.repos.d/emqx.repo
      {%- endif -%}

- name: Remove APT cache
  ansible.builtin.file:
    path: /var/lib/apt/lists/
    state: absent
  when: ansible_os_family == 'Debian'

- name: Recreate APT cache directory
  ansible.builtin.file:
    path: /var/lib/apt/lists/
    state: directory
    mode: '0755'
  when: ansible_os_family == 'Debian'
