---
- name: Converge
  hosts: all
  become: true

  pre_tasks:
    - name: Update package cache (Debian)
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 7200
      when: ansible_os_family == 'Debian'

  roles:
    - role: ansible-role-emqx
