---
- name: Restart EMQX
  ansible.builtin.service:
    name: emqx
    state: restarted
    enabled: "{{ emqx_service_enabled }}"
  listen: Restart EMQX

- name: Restart Chronyd
  ansible.builtin.service:
    name: chronyd
    state: restarted
  listen: Restart Chronyd
