---
- name: Install and configure EMQX
  hosts: all
  become: true
  vars:
    # EMQX version
    emqx_version: "5.8.3"

    # Service configuration
    emqx_service_state: started
    emqx_service_enabled: true

    # Cluster configuration
    emqx_cluster_discovery_strategy: static

    # Port settings
    emqx_tcp_port: 1883
    emqx_ssl_port: 8883
    emqx_ws_port: 0
    emqx_wss_port: 0
    emqx_dashboard_http_port: 18083

  roles:
    - role: ../../ansible-role-emqx
