---
- name: Create temporary directory for package
  ansible.builtin.file:
    path: "/tmp/emqx-{{ emqx_version }}"
    state: directory
    mode: '0755'

- name: Set package variables
  ansible.builtin.set_fact:
    pkg_arch: "{% if ansible_architecture == 'aarch64' %}arm64{% else %}amd64{% endif %}"
    pkg_name: >-
      emqx-{{ emqx_version }}-{%- if ansible_distribution | lower == 'debian' -%}debian{{ ansible_distribution_major_version }}{%- else -%}ubuntu{{ ansible_distribution_version }}{%- endif -%}

- name: Set package path and URLs
  ansible.builtin.set_fact:
    pkg_path: >-
      /tmp/emqx-{{ emqx_version }}/{{ pkg_name }}-{{ pkg_arch }}.deb
    pkg_url: >-
      https://www.emqx.com/en/downloads/broker/{{ emqx_version }}/{{ pkg_name }}-{{ pkg_arch }}.deb
    pkg_checksum_url: >-
      https://www.emqx.com/en/downloads/broker/{{ emqx_version }}/{{ pkg_name }}-{{ pkg_arch }}.deb.sha256

- name: Get package checksum
  ansible.builtin.set_fact:
    pkg_checksum: "{{ lookup('ansible.builtin.url', pkg_checksum_url) }}"

- name: Check if package exists and verify checksum
  ansible.builtin.stat:
    path: "{{ pkg_path }}"
    checksum_algorithm: sha256
  register: pkg_stat

- name: Download EMQX deb package
  ansible.builtin.get_url:
    url: "{{ pkg_url }}"
    dest: "{{ pkg_path }}"
    checksum: "sha256:{{ pkg_checksum }}"
    mode: '0644'
  when: >
    not pkg_stat.stat.exists or
    pkg_stat.stat.checksum is undefined or
    pkg_stat.stat.checksum != pkg_checksum

- name: Install EMQX from deb package
  ansible.builtin.apt:
    deb: "{{ pkg_path }}"
    state: "{{ emqx_package_state }}"
