---
name: Molecule CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 6 * * 0'  # Run every Sunday at 6 AM UTC

jobs:
  molecule:
    name: Molecule
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        distro:
          - debian11
          - debian12
          - ubuntu2004
          - ubuntu2204
          - amazonlinux2
          - amazonlinux2023
          - rockylinux8
          - rockylinux9
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          ./scripts/setup-test-env.sh

      - name: Display versions
        run: |
          python3 -m venv venv
          source venv/bin/activate
          python --version
          ansible --version
          molecule --version

      - name: Run Molecule tests
        run: |
          python3 -m venv venv
          source venv/bin/activate
          # Try static scenario
          for i in {1..3}; do
            echo "Attempt static $i of 3"
            if MOLECULE_DISTRO=${{ matrix.distro }} molecule test -s static; then
              break
            fi
            echo "Attempt static $i failed, retrying..."
            sleep 15
          done

          # Try manual scenario
          for i in {1..3}; do
            echo "Attempt manual $i of 3"
            if MOLECULE_DISTRO=${{ matrix.distro }} molecule test -s manual; then
              exit 0
            fi
            echo "Attempt manual $i failed, retrying..."
            sleep 15
          done
          exit 1
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}
          MOLECULE_NO_LOG: false

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: molecule-results-${{ matrix.distro }}
          path: |
            molecule/default/molecule.yml
            molecule/default/*.log
            molecule/default/reports/
